name: getx_shop_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage:
  intl: ^0.17.0
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/placeholder.png
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets\Comfortaa-VariableFont_wght.ttf

    - family: Shizuru
      fonts:
        - asset: assets\Shizuru-Regular.ttf

  uses-material-design: true



